version: '3.8'

services:
  springboot_app_chat:
    build: .
    ports:
      - "18089:8089"  # puerto externo : puerto interno
    container_name: springboot_app_chat
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/chat_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SERVER_PORT: 8089
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: postgres_chat
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_chat
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@chat.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "15050:80"
    depends_on:
      - db
    restart: always

volumes:
  pgdata: